---
title: Kmccabe.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  faqs:
    title: Faqs
    output: true
name: Kevin McCabe's Notes on Computational Experimental Economics
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-cayman